// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00r9gSOgnI7rEx2SGU0xY1-0WzeFgrwg',
    appId: '1:1089543914876:web:a38c06a07bfe81f93c10f9',
    messagingSenderId: '1089543914876',
    projectId: 'neuropy-flutter',
    authDomain: 'neuropy-flutter.firebaseapp.com',
    storageBucket: 'neuropy-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEoB90jzBbtTviyoy1dVdpYS09Fe1Qo-8',
    appId: '1:1089543914876:android:43c341855f7dca933c10f9',
    messagingSenderId: '1089543914876',
    projectId: 'neuropy-flutter',
    storageBucket: 'neuropy-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9pNrQo2wsNwLK7Bl2HQxjyn3peI7ISPE',
    appId: '1:1089543914876:ios:68c08ba4ac26306e3c10f9',
    messagingSenderId: '1089543914876',
    projectId: 'neuropy-flutter',
    storageBucket: 'neuropy-flutter.firebasestorage.app',
    iosBundleId: 'com.example.neuropyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9pNrQo2wsNwLK7Bl2HQxjyn3peI7ISPE',
    appId: '1:1089543914876:ios:68c08ba4ac26306e3c10f9',
    messagingSenderId: '1089543914876',
    projectId: 'neuropy-flutter',
    storageBucket: 'neuropy-flutter.firebasestorage.app',
    iosBundleId: 'com.example.neuropyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC00r9gSOgnI7rEx2SGU0xY1-0WzeFgrwg',
    appId: '1:1089543914876:web:02ea153e907b59273c10f9',
    messagingSenderId: '1089543914876',
    projectId: 'neuropy-flutter',
    authDomain: 'neuropy-flutter.firebaseapp.com',
    storageBucket: 'neuropy-flutter.firebasestorage.app',
  );
}
